import torch
import torch.nn as nn
import torch.nn.functional as F
from .hypernetwork import FractalHyperNet
from .tzimtzum import TzimtzumLayer

class OlamLayerResearch(nn.Module):
    """
    Layer representing one full 'World' (10 Sefirot).
    Uses the hypernetwork to obtain the weights of its Sefirot.
    """
    def __init__(self, world_idx: int, d_model: int, hypernet: FractalHyperNet, weight_mode: str = 'hyper'):
        super().__init__()
        self.world_idx = world_idx
        self.d_model = d_model
        self.hypernet = hypernet
        self.num_nodes = 10
        self.weight_mode = weight_mode

        # ABLATION 'direct': per-node weights are DIRECT parameters (not generated by the hypernet),
        # to test whether weight sharing by generation explains the gap to the baseline.
        if weight_mode == 'direct':
            self.W_direct = nn.Parameter(torch.randn(self.num_nodes, d_model, d_model) * (d_model ** -0.5))

        # The "22 paths" are a learned 10x10 adjacency matrix (trained by ordinary backpropagation)
        self.adj_logits = nn.Parameter(torch.randn(self.num_nodes, self.num_nodes))
        self.phi = nn.Linear(d_model, d_model, bias=False)
        self.norm = nn.LayerNorm(d_model)

    def forward(self, x: torch.Tensor, steps: int = 1) -> torch.Tensor:
        for _ in range(steps):
            x_new = torch.zeros_like(x)
            alpha = F.softmax(self.adj_logits, dim=-1)

            for k in range(self.num_nodes):
                # A. Get the weights: generated (hyper) or direct (ablation)
                if self.weight_mode == 'direct':
                    W_k = self.W_direct[k]
                else:
                    W_k = self.hypernet(self.world_idx, k)

                # B. Local computation of Sefirah k
                h_k = F.linear(self.norm(x[:, k, :]), W_k)

                # C. Message routing through the learned adjacency
                messages = self.phi(x)
                weighted_messages = torch.einsum('n,bnd->bd', alpha[:, k], messages)

                # D. Integration
                x_new[:, k, :] = x[:, k, :] + F.gelu(h_k) + weighted_messages
            x = x_new
        return x

class EtzChaimFractalAI(nn.Module):
    """
    The unified research architecture. Ablations are selected with switches
    (num_worlds, tzimtzum_active, weight_mode, tzimtzum_mode).
    """
    def __init__(self, d_model: int = 64, num_worlds: int = 4, tzimtzum_active: bool = True,
                 weight_mode: str = 'hyper', tzimtzum_mode: str = 'fixed', hyper_init: str = 'default'):
        super().__init__()
        self.d_model = d_model
        self.num_worlds = num_worlds
        self.tzimtzum_active = tzimtzum_active
        self.tzimtzum_mode = tzimtzum_mode

        # The central "genome" (useless in 'direct' mode: it is not created, for a clean ablation)
        self.hypernet = None if weight_mode == 'direct' else FractalHyperNet(base_dim=self.d_model, n_worlds=num_worlds)
        # hyper_init='calibrated': start the generated weights at the scale of the 'direct' ablation
        if self.hypernet is not None and hyper_init == 'calibrated':
            self.hypernet.calibrate_init(num_worlds)

        # The Worlds (Atzilut, Beriah, Yetzirah, Assiyah)
        self.worlds = nn.ModuleList([
            OlamLayerResearch(i, self.d_model, self.hypernet, weight_mode=weight_mode) for i in range(num_worlds)
        ])

        # The contraction points (Tzimtzum)
        if self.tzimtzum_active:
            self.tzimtzums = nn.ModuleList([
                TzimtzumLayer(self.d_model, self.d_model // 2, self.d_model) for _ in range(max(0, num_worlds - 1))
            ])
            self.expanders = nn.ModuleList([
                nn.Linear(self.d_model // 2, self.d_model) for _ in range(max(0, num_worlds - 1))
            ])
            # ABLATION 'gated': one learned gate per world decides how much bottleneck to apply
            # (g->0 = bypass the Tzimtzum, g->1 = full compression). Init 0 -> sigmoid=0.5.
            if tzimtzum_mode == 'gated':
                self.gates = nn.ParameterList([
                    nn.Parameter(torch.zeros(1)) for _ in range(max(0, num_worlds - 1))
                ])

    def forward(self, x_atzilut: torch.Tensor, intent_signal: torch.Tensor):
        x = x_atzilut
        total_intent_loss = torch.tensor(0.0, device=x.device)

        # Pass 1: Atzilut
        x = self.worlds[0](x)

        # Passes 2..N
        for i in range(1, self.num_worlds):
            if self.tzimtzum_active:
                # Compression + Keter (intent reconstruction) loss
                x_compressed, intent_loss = self.tzimtzums[i-1](x, intent_signal)
                total_intent_loss += intent_loss
                x_expanded = self.expanders[i-1](x_compressed)
                if self.tzimtzum_mode == 'gated':
                    g = torch.sigmoid(self.gates[i-1])          # learned gate: bottleneck vs passthrough
                    x = g * x_expanded + (1.0 - g) * x
                else:
                    x = x_expanded

            # Apply this world's update
            x = self.worlds[i](x)

        return x, total_intent_loss
